### ISSUE TITLE
Cannot find module 'graphql-playground/middleware'

### ISSUE THREAD

**Issue by stantoncbradley** [AgarthaSolutions/graphcool-gateway-apollo-engine-demo#1]
App immediately crashes when I run any of the start scripts. There is some kind of issue importing `graphql-playground/middleware`.

```
➜  graphcool-gateway-apollo-engine-demo git:(master) yarn start
yarn start v0.22.0
$ nodemon --ext ts --exec node ./node_modules/ts-node/dist/bin index.ts
[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./node_modules/ts-node/dist/bin index.ts`

/xxx/graphcool-gateway-apollo-engine-demo/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
index.ts (10,39): Cannot find module 'graphql-playground/middleware'. (2307)
    at getOutput (/xxx/graphcool-gateway-apollo-engine-demo/node_modules/ts-node/src/index.ts:307:15)
    at xxx/graphcool-gateway-apollo-engine-demo/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/xxx/graphcool-gateway-apollo-engine-demo/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/xxx/graphcool-gateway-apollo-engine-demo/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/xxx/graphcool-gateway-apollo-engine-demo/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by kbrandwijk** [comment]
The new version of `graphql-playground` has a new structure. The playground for Express has moved to `graphql-playground-middleware`. I'll push an update today.

**Comment by kbrandwijk** [comment]
Thank you for reporting. Fixed in 1d94ffd

**Comment by stantoncbradley** [comment]
thanks for fixing this so quickly! the Apollo APIs aren't returning any data for me?  If you are not the person to ask about this, maybe you know someone I can talk to?
```
'https://api.graph.cool/simple/v1/apollo-engine-demo-posts'
```
```
query {
  allFiles {
    contentType
    createdAt
    id
    name
    secret
  }
}
```
```
{
  "data": {
    "allFiles": []
  }
}
```

**Comment by kbrandwijk** [comment]
Yes, I made the endpoints. You just happened to pick a Type without any nodes. Did you try any of the queries from the readme, or for example:
```
query {
  allPosts{
    id
    title
  }
}
```
Those all return records for me.

**Comment by stantoncbradley** [comment]
ah ok awesome!  Yeah I tried `allUsers` and `user` and didn't get anything either.  That query works though.  As long as some of them work I'm good!  Thanks!!

**Comment by kbrandwijk** [comment]
Glad it's working for you. The endpoints are just very minimal to demonstrate the point about Apollo Engine in this case. You can easily swap them out for your own GraphQL endpoints.
